collections:
  - th_pubs_collection

name: "Alex St Laurent"
author: "Alexander St Laurent"
description: "Alex's personal site"
keywords: "Brown, Brown University, Math, Mathematics, Programming, Programmer, Software, Computer, Computers, Computer Science, Javascript, HTML, CSS, Bootstrap, Java, Python, Git"
name_smallcaps: "<span style='font-variant:small-caps;'>alex st laurent</span>"

font_family: "Ubuntu"
font_cdn: "https://fonts.googleapis.com/css?family=Ubuntu"

url: "localhost:4000"

paginate: 10

markdown: rdiscount
permalink: pretty

index_title: "Alex St Laurent"
resume_title: "Resume"
math_title: "Math"
programming_title: "Programming"
contact_title: "Contact"

img_dir: "/images/"

index_logo: "logo-thumb.png"
resume_logo: "reslogo-thumb.png"
math_logo: "mathlogo-thumb.png"
programming_logo: "proglogo-thumb.png"
contact_logo: "contactlogo-thumb.png"

shortcut_icon: "/images/favicon.ico"
jquery_cdn: "https://code.jquery.com/jquery-2.1.1.min.js"
jqueryui_cdn: "https://code.jquery.com/ui/1.11.0/jquery-ui.min.js"
font_awesome_css: "/css/font-awesome.css"

