name: "Alexander St Laurent"
author: "Alexander St Laurent"
description: "Alex's personal site"
keywords: "Brown, Brown University, Math, Mathematics, Programming, Programmer, Software, Computer, Computers, Computer Science, Javascript, HTML, CSS, Bootstrap, Java, Python, Git"
chartset: "utf-8"


url: "localhost:4000"

baseurl: "/~awstlaur"

paginate: 10

markdown: rdiscount
permalink: pretty

index_title: "Alexander St Laurent"
resume_title: "Resume"
math_title: "Math"
programming_title: "Programming"
contact_title: "Contact"

shortcut_icon: "/images/favicon.ico"
jquery_cdn: "http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"