source: "docs"
destination: "_site"

name: "Alex St Laurent"
author: "Alexander St Laurent"
description: "Alex's personal site"
keywords: "Brown, Brown University, Math, Mathematics, Programming, Programmer, Software, Computer, Computers, Computer Science, Javascript, HTML, CSS, Bootstrap, Perl, Java, Python, Git"
name_smallcaps: "<span style='font-variant:small-caps;'>alex st laurent</span>"

url: "localhost:4000"

markdown: rdiscount
permalink: pretty

index_title: "Alex St Laurent"
resume_title: "Resume"
math_title: "Math"
programming_title: "Programming"
contact_title: "Contact"

img_dir: "/images/"

index_logo: "logo.png"
resume_logo: "reslogo.png"
math_logo: "mathlogo.png"
programming_logo: "proglogo.png"
contact_logo: "contactlogo.png"

shortcut_icon: "/images/favicon.ico"
jquery_js: "https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"
jqueryui_js: "https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.4/i18n/jquery-ui-i18n.min.js"
font_awesome_css: "https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css"
style_css: "/css/style.css"

